import hashlib
import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from .models import Incident, ForensicPackage

FORENSICS_DIR = Path("data/forensics")


class EvidenceCollector:
    def collect(self, incident: Incident) -> ForensicPackage:
        case_dir = FORENSICS_DIR / incident.id
        case_dir.mkdir(parents=True, exist_ok=True)
        evidence_dir = case_dir / "evidence"
        evidence_dir.mkdir(exist_ok=True)
        manifest = []
        timeline = [
            {"time": incident.timestamp, "event": f"Incident detected: {incident.attack_type}"},
            {"time": datetime.now(timezone.utc).isoformat(), "event": "Evidence collection started"},
        ]
        steps = [
            ("log_context.txt", self._capture_log_context(incident)),
            ("connection_state.txt", self._capture_connections()),
            ("process_snapshot.txt", self._capture_processes()),
            ("incident.json", json.dumps(incident.model_dump(), indent=2)),
        ]
        for fname, content in steps:
            if content:
                path = evidence_dir / fname
                path.write_text(content, encoding="utf-8")
                h = hashlib.sha256(content.encode()).hexdigest()
                manifest.append({"file": fname, "path": str(path), "sha256": h})
                timeline.append({
                    "time": datetime.now(timezone.utc).isoformat(),
                    "event": f"Collected evidence: {fname}",
                })
        report = self._generate_report(incident, manifest, timeline)
        report_path = case_dir / "report.md"
        report_path.write_text(report, encoding="utf-8")
        manifest.append({"file": "report.md", "path": str(report_path), "sha256": hashlib.sha256(report.encode()).hexdigest()})
        chain = self._chain_of_custody(incident.id, manifest)
        chain_path = case_dir / "chain_of_custody.log"
        chain_path.write_text(chain, encoding="utf-8")
        pkg = ForensicPackage(
            incident_id=incident.id,
            evidence_manifest=manifest,
            timeline=timeline,
            chain_of_custody=chain,
            report_path=str(report_path),
        )
        pkg_path = case_dir / "package.json"
        pkg_path.write_text(json.dumps(pkg.model_dump(), indent=2), encoding="utf-8")
        return pkg

    def _capture_log_context(self, incident: Incident) -> str:
        return f"Log snippet:\n{incident.log_snippet}" if incident.log_snippet else "No log available"

    def _capture_connections(self) -> str:
        try:
            if sys.platform == "win32":
                r = subprocess.run(["netstat", "-an"], capture_output=True, text=True, timeout=5)
            else:
                r = subprocess.run(["ss", "-tupn"], capture_output=True, text=True, timeout=5)
            return r.stdout
        except Exception as e:
            return f"Failed to capture connections: {e}"

    def _capture_processes(self) -> str:
        try:
            if sys.platform == "win32":
                r = subprocess.run(["tasklist"], capture_output=True, text=True, timeout=5)
            else:
                r = subprocess.run(["ps", "aux"], capture_output=True, text=True, timeout=5)
            return r.stdout
        except Exception as e:
            return f"Failed to capture processes: {e}"

    @staticmethod
    def _generate_report(incident: Incident, manifest: list, timeline: list) -> str:
        lines = []
        lines.append("INCIDENT FORENSIC REPORT")
        lines.append("=" * 50)
        lines.append(f"Case ID: INC-{incident.id}")
        lines.append(f"Generated: {datetime.now(timezone.utc).isoformat()}")
        lines.append(f"Generated By: Artenisa Defense Module")
        lines.append("")
        lines.append("1. EXECUTIVE SUMMARY")
        lines.append(f"   - Attack Type: {incident.attack_type}")
        lines.append(f"   - Source IP: {incident.source_ip}")
        lines.append(f"   - Target: {incident.target}")
        lines.append(f"   - Detected: {incident.timestamp}")
        lines.append(f"   - Severity: {incident.severity}")
        lines.append(f"   - Status: {incident.status}")
        lines.append("")
        if incident.threat_intel:
            lines.append("2. ATTACKER INTELLIGENCE")
            ti = incident.threat_intel
            lines.append(f"   - ISP: {ti.isp or 'Unknown'}")
            lines.append(f"   - Country: {ti.country or 'Unknown'}")
            lines.append(f"   - ASN: {ti.asn or 'Unknown'}")
            lines.append(f"   - Abuse Reports: {ti.abuse_reports}")
            lines.append(f"   - Confidence: {ti.confidence}%")
            lines.append("")
        lines.append("3. TIMELINE")
        for entry in timeline:
            lines.append(f"   [{entry['time']}] {entry['event']}")
        lines.append("")
        lines.append("4. EVIDENCE MANIFEST")
        for m in manifest:
            lines.append(f"   - {m['file']}: SHA256 {m['sha256'][:16]}...")
        lines.append("")
        lines.append("5. CHAIN OF CUSTODY")
        lines.append("   Evidence collected by: Artenisa Defense Module")
        lines.append("   All evidence hashed and timestamped.")
        lines.append("")
        lines.append("=" * 50)
        return "\n".join(lines)

    @staticmethod
    def _chain_of_custody(case_id: str, manifest: list) -> str:
        lines = [
            f"Chain of Custody - Case INC-{case_id}",
            f"Started: {datetime.now(timezone.utc).isoformat()}",
            "=" * 40,
        ]
        for m in manifest:
            lines.append(f"File: {m['file']}")
            lines.append(f"Path: {m['path']}")
            lines.append(f"SHA256: {m['sha256']}")
            lines.append(f"Access: Artenisa Defense Module")
            lines.append("-" * 20)
        return "\n".join(lines)
